sudo: false
language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      - build-essential
      - libnss3
      - libnss3-dev

script:
- |
  cargo build &&
  cargo test